name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce the issue.

  - type: input
    id: app_version
    attributes:
      label: App version
      description: The version shown in the app (or from GitHub release)
      placeholder: "e.g. 0.0.50"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: adb_version
    attributes:
      label: ADB version
      description: Paste the output of `adb version`
      placeholder: "Android Debug Bridge version ..."
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps are easiest to follow
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Please redact any secrets, tokens, or personal information.
    validations:
      required: false
