name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the problem you're trying to solve and what a good solution looks like.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      placeholder: "As a user, I want to..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "What should the app do?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false
